CREATE TABLE IF NOT EXISTS client_models (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  deleted_at DATETIME(3) NULL,
  tenant_id VARCHAR(36) NOT NULL,
  model_key VARCHAR(80) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  provider VARCHAR(16) NOT NULL,
  scope VARCHAR(16) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order BIGINT NOT NULL DEFAULT 0,
  supported_modes JSON NULL,
  supported_scopes JSON NULL,
  aspect_ratios JSON NULL,
  durations JSON NULL,
  note VARCHAR(256) NULL,
  KEY idx_client_model_key (tenant_id, model_key, provider, scope),
  KEY idx_client_models_tenant (tenant_id),
  KEY idx_client_models_deleted_at (deleted_at),
  KEY idx_client_models_provider (provider),
  KEY idx_client_models_scope (scope),
  KEY idx_client_models_enabled (enabled),
  KEY idx_client_models_sort_order (sort_order)
);

CREATE TABLE IF NOT EXISTS client_model_routes (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  deleted_at DATETIME(3) NULL,
  tenant_id VARCHAR(36) NOT NULL,
  client_model_id VARCHAR(36) NOT NULL,
  credential_id VARCHAR(36) NOT NULL,
  upstream_model VARCHAR(120) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  priority BIGINT NOT NULL DEFAULT 0,
  sort_order BIGINT NOT NULL DEFAULT 0,
  note VARCHAR(256) NULL,
  KEY idx_client_model_routes_tenant (tenant_id),
  KEY idx_client_model_routes_deleted_at (deleted_at),
  KEY idx_client_model_routes_client_model_id (client_model_id),
  KEY idx_client_model_routes_credential_id (credential_id),
  KEY idx_client_model_routes_enabled (enabled),
  KEY idx_client_model_routes_is_default (is_default),
  KEY idx_client_model_routes_priority (priority),
  KEY idx_client_model_routes_sort_order (sort_order)
);
